import React, { useState, useEffect } from 'react';
import { AIFeature } from '../types';
import { AI_FEATURES } from '../data/mockData';
import { X, Sparkles, Send, Copy, Check, RefreshCw, Terminal, Cpu, Bot, User, CornerDownLeft, ShieldCheck, Lock, Crown, ArrowRight } from 'lucide-react';
import { useEcosystem, useUser } from '../context/EcosystemContext';
import { SpaceChatSkeleton } from './SpaceSkeletonLoader';

interface AISandboxModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialFeature?: AIFeature;
  onOpenPaymentModal?: () => void;
}

export const AISandboxModal: React.FC<AISandboxModalProps> = ({
  isOpen,
  onClose,
  initialFeature,
  onOpenPaymentModal,
}) => {
  const { incrementAiTasks } = useEcosystem();
  const { user, isSubscribed, incrementUserAiTasks } = useUser();
  const [selectedFeature, setSelectedFeature] = useState<AIFeature>(
    initialFeature || AI_FEATURES[0]
  );
  const [prompt, setPrompt] = useState<string>('');
  const [output, setOutput] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);
  const [chatHistory, setChatHistory] = useState<Array<{ role: 'user' | 'ai'; text: string; time: string }>>([]);

  useEffect(() => {
    const welcomeUserText = user 
      ? `Hello ${user.name}! I am Creatiq AI Brain connected to your ${user.role} workspace session.` 
      : 'Welcome to Creatiq AI Brain Sandbox.';

    if (initialFeature) {
      setSelectedFeature(initialFeature);
      setPrompt(initialFeature.samplePrompt);
      setOutput(initialFeature.demoOutput);
      setChatHistory([
        { role: 'user', text: initialFeature.samplePrompt, time: 'Just now' },
        { role: 'ai', text: `${welcomeUserText}\n\n${initialFeature.demoOutput}`, time: 'Just now' }
      ]);
    } else {
      setPrompt(AI_FEATURES[0].samplePrompt);
      setOutput(AI_FEATURES[0].demoOutput);
      setChatHistory([
        { role: 'user', text: AI_FEATURES[0].samplePrompt, time: 'Just now' },
        { role: 'ai', text: `${welcomeUserText}\n\n${AI_FEATURES[0].demoOutput}`, time: 'Just now' }
      ]);
    }
  }, [initialFeature, isOpen, user]);

  if (!isOpen) return null;

  const isCurrentToolLocked = selectedFeature.isLocked && !isSubscribed;

  const handleSelectTool = (feature: AIFeature) => {
    setSelectedFeature(feature);
    setPrompt(feature.samplePrompt);
    setOutput(feature.demoOutput);
    setChatHistory([
      { role: 'user', text: feature.samplePrompt, time: 'Just now' },
      { role: 'ai', text: feature.demoOutput, time: 'Just now' }
    ]);
  };

  const handleGenerate = async () => {
    if (isCurrentToolLocked) {
      if (onOpenPaymentModal) onOpenPaymentModal();
      return;
    }

    if (!prompt.trim() || isGenerating) return;

    setIsGenerating(true);
    const newHistory = [...chatHistory, { role: 'user' as const, text: prompt, time: 'Just now' }];
    setChatHistory(newHistory);

    try {
      // Call local backend endpoint if available, or generate context-aware simulated response
      const res = await fetch('/api/ai/sandbox', {
        method: 'POST',
        headers: { 'Content-[#Type]': 'application/json', 'Content-Type': 'application/json' },
        body: JSON.stringify({ toolId: selectedFeature.id, prompt })
      }).catch(() => null);

      if (res && res.ok) {
        const data = await res.json();
        const responseText = data.output || selectedFeature.demoOutput;
        setOutput(responseText);
        setChatHistory([...newHistory, { role: 'ai' as const, text: responseText, time: 'Just now' }]);
        incrementAiTasks();
        incrementUserAiTasks();
      } else {
        // Fallback simulated intelligent response
        setTimeout(() => {
          let simulatedText = `[Creatiq ${selectedFeature.title} v3.0 Processing Completed]\n\nBased on your query: "${prompt}"\n\n`;
          
          if (selectedFeature.id === 'ai-coding' || selectedFeature.id === 'ai-website-builder') {
            simulatedText += "```typescript\n// Generated by Creatiq AI Coding Engine\nexport function solveQuery() {\n  console.log('Optimized solution initialized for: " + prompt + "');\n  return { success: true, timestamp: new Date().toISOString() };\n}\n```";
          } else if (selectedFeature.id === 'ai-image-gen') {
            simulatedText += `✨ Image Rendered: 4K Ultra-Res Artwork generated successfully. Rendering depth pass, neon cyan volumetric lighting, and glass opacity reflection layers.`;
          } else {
            simulatedText += `Here is your customized result:\n\n1. Executive Summary: Optimized approach formulated for maximum clarity and speed.\n2. Actionable Output: Creatiq memory vault synced and ready for export to workspace notes.\n3. Next Step: You can continue this discussion or send follow-up questions.`;
          }

          setOutput(simulatedText);
          setChatHistory([...newHistory, { role: 'ai' as const, text: simulatedText, time: 'Just now' }]);
          setIsGenerating(false);
          incrementAiTasks();
          incrementUserAiTasks();
        }, 800);
        return;
      }
    } catch (e) {
      setOutput(selectedFeature.demoOutput);
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-950/80 backdrop-blur-xl animate-in fade-in duration-200">
      <div className="relative w-full max-w-5xl h-[85vh] bg-slate-950 border border-slate-800 rounded-3xl shadow-2xl flex flex-col overflow-hidden">
        
        {/* Modal Header */}
        <div className="px-6 py-4 bg-slate-900/90 border-b border-slate-800 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 flex items-center justify-center text-white shadow-lg">
              <Cpu className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-extrabold text-white">Creatiq AI Sandbox</h3>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
                  LIVE DEMO
                </span>
              </div>
              <p className="text-xs text-slate-400">Test any of Creatiq’s 15 AI engines in real time</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {user && (
              <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-xl bg-slate-950 border border-slate-800 text-xs">
                <img src={user.avatar} alt={user.name} className="w-5 h-5 rounded-full border border-cyan-500/40" />
                <span className="font-bold text-slate-200">{user.name}</span>
                <span className="text-[10px] text-cyan-400 font-mono">({user.role})</span>
              </div>
            )}

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Main Body */}
        <div className="flex-1 grid grid-cols-1 md:grid-cols-12 overflow-hidden">
          
          {/* Left Sidebar: Tool Selector */}
          <div className="md:col-span-4 bg-slate-950 border-r border-slate-800/80 p-4 overflow-y-auto space-y-2 text-xs hidden md:block">
            <span className="text-[10px] uppercase font-mono font-bold text-slate-500 tracking-wider px-2 block mb-2">
              Select AI Engine
            </span>
            {AI_FEATURES.map((tool) => {
              const isLocked = tool.isLocked && !isSubscribed;
              return (
                <button
                  key={tool.id}
                  onClick={() => handleSelectTool(tool)}
                  className={`w-full p-3 rounded-xl text-left transition-all flex items-center justify-between ${
                    selectedFeature.id === tool.id
                      ? isLocked
                        ? 'bg-gradient-to-r from-amber-950 to-purple-950 border border-amber-500/50 text-white shadow-lg'
                        : 'bg-gradient-to-r from-cyan-950 to-purple-950 border border-cyan-500/40 text-white shadow-lg'
                      : isLocked
                      ? 'text-amber-300/70 hover:text-amber-200 hover:bg-amber-950/20 border border-amber-500/20'
                      : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900/60 border border-transparent'
                  }`}
                >
                  <div className="flex-1 min-w-0 pr-2">
                    <div className="font-bold text-slate-200 flex items-center gap-1.5 truncate">
                      <span>{tool.title}</span>
                      {isLocked && <Lock className="w-3 h-3 text-amber-400 shrink-0" />}
                    </div>
                    <div className="text-[10px] text-slate-500 line-clamp-1">{tool.subtitle}</div>
                  </div>
                  
                  {isLocked ? (
                    <span className="px-1.5 py-0.5 rounded text-[9px] font-black bg-amber-500/20 text-amber-300 border border-amber-500/30 shrink-0">
                      PRO
                    </span>
                  ) : selectedFeature.id === tool.id ? (
                    <Sparkles className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
                  ) : null}
                </button>
              );
            })}
          </div>

          {/* Right Main Sandbox Chat & Output Area */}
          <div className="md:col-span-8 flex flex-col bg-slate-900/40 h-full overflow-hidden">
            
            {/* Active Tool Header Banner */}
            <div className={`px-6 py-3 border-b flex items-center justify-between text-xs ${
              isCurrentToolLocked
                ? 'bg-amber-950/40 border-amber-500/30'
                : 'bg-slate-900/60 border-slate-800/80'
            }`}>
              <div className="flex items-center gap-2">
                <span className={`font-bold ${isCurrentToolLocked ? 'text-amber-300' : 'text-cyan-300'}`}>
                  {selectedFeature.title}
                </span>
                <span className="text-slate-500">•</span>
                <span className="text-slate-400">{selectedFeature.subtitle}</span>
                {isCurrentToolLocked && (
                  <span className="ml-2 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 font-black text-[10px] flex items-center gap-1">
                    <Lock className="w-3 h-3" /> PRO LOCKED
                  </span>
                )}
              </div>
              <button
                onClick={() => setPrompt(selectedFeature.samplePrompt)}
                className="text-cyan-400 hover:underline flex items-center gap-1 text-[11px]"
              >
                <RefreshCw className="w-3 h-3" />
                Load Sample Prompt
              </button>
            </div>

            {/* Locked Subscription Banner Notice inside Chat */}
            {isCurrentToolLocked && (
              <div className="mx-6 mt-4 p-4 rounded-2xl bg-gradient-to-r from-amber-950/80 via-slate-900 to-purple-950/80 border border-amber-500/40 text-center space-y-3 shadow-xl">
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-bold border border-amber-500/30">
                  <Lock className="w-3.5 h-3.5 text-amber-400 animate-pulse" />
                  Top 8 Most Used AI Tool Locked
                </div>
                <h4 className="text-base font-extrabold text-white">
                  First Buy a Subscription to Use {selectedFeature.title}
                </h4>
                <p className="text-xs text-slate-300 max-w-lg mx-auto leading-relaxed">
                  This tool is one of Creatiq's top 8 most popular AI capabilities. Buy a Pro subscription (starting at ₹99/mo) to unlock full prompt execution and output generation.
                </p>
                <button
                  onClick={() => {
                    if (onOpenPaymentModal) onOpenPaymentModal();
                  }}
                  className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 via-cyan-500 to-purple-600 text-slate-950 font-black text-xs hover:scale-105 transition-all shadow-lg shadow-amber-950/50 inline-flex items-center gap-2"
                >
                  <Crown className="w-4 h-4" />
                  <span>Buy Subscription Now (Starting at ₹99/mo)</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            )}

            {/* Conversation Messages */}
            <div className="flex-1 p-6 overflow-y-auto space-y-4 text-xs font-sans">
              {chatHistory.map((msg, index) => (
                <div
                  key={index}
                  className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  {msg.role === 'ai' && (
                    <div className="w-7 h-7 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-300 shrink-0 mt-0.5">
                      <Bot className="w-4 h-4" />
                    </div>
                  )}

                  <div
                    className={`max-w-[85%] rounded-2xl p-4 leading-relaxed ${
                      msg.role === 'user'
                        ? 'bg-gradient-to-r from-cyan-600 to-blue-600 text-white rounded-tr-none shadow-md'
                        : 'bg-slate-950 border border-slate-800 text-slate-200 rounded-tl-none font-mono text-[11px] whitespace-pre-wrap'
                    }`}
                  >
                    <div className="flex items-center justify-between gap-4 mb-1 pb-1 border-b border-slate-800/40 text-[10px] opacity-70">
                      <span className="font-bold">{msg.role === 'user' ? 'You' : `Creatiq ${selectedFeature.title}`}</span>
                      <span>{msg.time}</span>
                    </div>
                    {msg.text}
                  </div>

                  {msg.role === 'user' && (
                    <div className="w-7 h-7 rounded-lg bg-slate-800 flex items-center justify-center text-slate-300 shrink-0 mt-0.5">
                      <User className="w-4 h-4" />
                    </div>
                  )}
                </div>
              ))}

              {isGenerating && (
                <div className="py-2">
                  <SpaceChatSkeleton />
                </div>
              )}
            </div>

            {/* Prompt Input Control Box */}
            <div className="p-4 bg-slate-950 border-t border-slate-800/80">
              <div className="relative">
                <textarea
                  rows={2}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleGenerate();
                    }
                  }}
                  placeholder={`Ask Creatiq ${selectedFeature.title} anything...`}
                  className="w-full bg-slate-900 border border-slate-800 rounded-2xl pl-4 pr-12 py-3 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500/60 resize-none"
                />
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating || !prompt.trim()}
                  className="absolute right-3 bottom-3.5 p-2 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 text-white disabled:opacity-40 hover:opacity-90 transition-all shadow-md"
                >
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>

              <div className="flex items-center justify-between text-[10px] text-slate-500 mt-2 px-1">
                <span>Press <kbd className="px-1 py-0.5 rounded bg-slate-800 text-slate-300 font-mono">Enter</kbd> to execute</span>
                <span className="text-cyan-400 font-mono">99.9% Execution Speed</span>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
